### ISSUE TITLE
Certain files added to DB but not recognized by IPOD (Unicode problem?)

### ISSUE THREAD

**Issue by pelagial** [nims11/IPod-Shuffle-4g#6] opened 2015-12-01 19:28 UTC
This might be related to #4 

When syncing my files with rhythmbox and this script, I realized that some files are correctly added to the DB but the iPod does not recognize them and, for example skips the according playlist. 

I explored the issue a little bit further and I found that it occurs when non-standard characters like "ó" are found in the filename or an ID3 tag field. The interesting thing is, after I updated tags with Easytag for both v1 and v2 to be UTF-8, the file was recognized. 

I guess one can easily implement a function to rewrite the tags but I wanted to ask if someone else stumbled over the same problem and knows what actually is the problem.

**Comment by NicoHood** [comment] 2016-02-08 15:50
Can you please provide a sample mp3 file which is free for download but with wrong tags?

What happens if you use the rhythmbox ipod plugin (not mtp) to sync music? Is it then also broken?

**Comment by NicoHood** [comment] 2016-04-05 21:16
@nims11 please close this, as it is no longer valid

**Comment by nims11** [comment] 2016-04-06 10:51
Duplicate of issue #4

**Closed by nims11** 2016-04-06 10:51 UTC
